### Configure a variable for the web service base address.
### Use port 5081 for testing the Chapter 8 web service.
### Use port 5091 for testing the Chapter 9 web service.

@base_address = https://localhost:5081/api/products/

### Get first page of 10 products that are in stock and not discontinued.
GET {{base_address}}

### Get third page of 10 products that are in stock and not discontinued
GET {{base_address}}?page=3

### Get products that are out-of-stock but not discontinued
GET {{base_address}}outofstock

### Get products that are discontinued
GET {{base_address}}discontinued

### Get product 77
GET {{base_address}}77

### Get products that contain "man"
GET {{base_address}}man
