namespace Northwind.Grpc.Service;

// This will merge with the DecimalValue type generated by the
// gRPC tools in the obj\Debug\net8.0\Protos\Decimal.cs file.

public partial class DecimalValue
{
  private const decimal NanoFactor = 1_000_000_000;

  public DecimalValue(long units, int nanos)
  {
    Units = units;
    Nanos = nanos;
  }

  public static implicit operator decimal(DecimalValue grpcDecimal)
  {
    return grpcDecimal.Units + (grpcDecimal.Nanos / NanoFactor);
  }

  public static implicit operator DecimalValue(decimal value)
  {
    long units = decimal.ToInt64(value);
    int nanos = decimal.ToInt32((value - units) * NanoFactor);
    return new DecimalValue(units, nanos);
  }
}