### Configure a variable for the Azure Functions base address.
@base_address = http://localhost:5101/

### Get information about the NumbersToWordsFunction function.
GET {{base_address}}admin/functions/NumbersToWordsFunction

### Get information about the ScrapeAmazonFunction function.
GET {{base_address}}admin/functions/ScrapeAmazonFunction

### Make a manual request to the Timer function.
POST {{base_address}}admin/functions/ScrapeAmazonFunction
Content-Type: application/json

{}