### Configure a variable for the GraphQL service base address.
@base_address = https://localhost:5121/graphql

### Get all products in the specified category.
POST {{base_address}}
Content-Type: application/json

{
  "query" : "{productsInCategory(categoryId:8){productId productName unitsInStock}}"
}

### Get all categories.
POST {{base_address}}
Content-Type: application/json

{
  "query" : "{categories{id categoryName description}}"
}

### Get a category and its products using a variable.
POST {{base_address}}
Content-Type: application/json

{
  "query": "query categoryAndItsProducts($id: Int!){category(categoryId: $id){categoryId categoryName products{productId productName}}}",
  "variables": {"id":8}
}
