### Configure a variable for the web service base address.
@base_address = https://localhost:5084/catalog/

### Get all categories.
GET {{base_address}}categories HTTP/1.1

### Get the single category 3.
GET {{base_address}}categories(3)

### Get the single category 3 (alternate syntax).
GET {{base_address}}categories/3

### Get a count of the number of categories.
GET {{base_address}}categories/$count

### Get all products.
GET {{base_address}}products

### Get a count of the number of products.
GET {{base_address}}products/$count

### Get the single product 3.
GET {{base_address}}products(2)

### Get all suppliers.
GET {{base_address}}suppliers

### Get a count of the number of suppliers.
GET {{base_address}}suppliers/$count
